model:
  type: resnet50
dataset: cifar10
aug: fa_reduced_cifar10
cutout: 0
batch: 5 #128
epoch: 90 #270
lr: 0.05
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
  ema: 0
